# fly.toml app configuration file generated for hivemind-tti3sa on 2026-06-20T01:06:02Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hivemind-tti3sa'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile'

[env]
  HIVEMIND_PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'get'
    path = '/v1/health'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
