use hivemind::commands::{CommandContext, Commands};
use hivemind::events::{EventProvenance, TenantId};
use hivemind::ledger::EventLedger;
use hivemind::projector::memory::MemoryGraph;
use hivemind::projector::{rebuild_graph_for_tenant, GraphParams, GraphValue, GraphView};

pub type TestResult<T> = std::result::Result<T, Box<dyn std::error::Error>>;

/// Per-tenant data produced by `seed_tenant`, used in isolation assertions.
#[derive(Debug, Clone)]
pub struct TenantDataset {
    pub tenant_id: TenantId,
    pub name: &'static str,
    pub decision_ids: Vec<String>,
    pub evidence_id: String,
    pub hypothesis_id: String,
}

/// Seed a named tenant with 10 decisions (+ evidence + hypothesis) on the given ledger.
///
/// All IDs are generated by the commands layer; the returned `TenantDataset` provides
/// the concrete IDs for use in assertions.
pub fn seed_tenant<L: EventLedger>(ledger: &L, name: &'static str) -> TestResult<TenantDataset> {
    let tenant_id = TenantId::new(name).map_err(|e| format!("invalid tenant name: {e}"))?;
    let context = CommandContext::new(tenant_id.clone(), EventProvenance::cli());
    let commands = Commands::new_with_context(ledger, context);

    let evidence_id = commands.record_evidence(
        &format!("human:{name}-researcher"),
        &format!("Evidence from {name}: observed production behaviour requiring a decision"),
    )?;

    let hypothesis_id = commands.record_hypothesis(
        &format!("human:{name}-analyst"),
        &format!("Hypothesis for {name}: the observed behaviour is reproducible and addressable"),
    )?;

    let topics = ["architecture", "operations", "security", "product"];
    let mut decision_ids = Vec::with_capacity(10);

    for i in 1..=10usize {
        let topic = topics[(i - 1) % topics.len()];

        let opt_a = commands.record_option(
            &format!("human:{name}-planner"),
            &format!("Conservative {name} {i}"),
            &format!("{name} decision {i}: conservative option — minimal change"),
        )?;
        let opt_b = commands.record_option(
            &format!("human:{name}-planner"),
            &format!("Progressive {name} {i}"),
            &format!("{name} decision {i}: progressive option — full refactor"),
        )?;

        let (hyp_refs, ev_refs): (Vec<String>, Vec<String>) = if i == 3 {
            (vec![hypothesis_id.clone()], vec![evidence_id.clone()])
        } else {
            (vec![], vec![])
        };

        let decision_id = commands.propose_decision(
            &format!("human:{name}-planner"),
            &format!("{name}: choice #{i:02} — {topic}"),
            &format!("Rationale for {name} decision {i}: {topic} tradeoff evaluated"),
            &[topic.to_owned()],
            &[opt_a, opt_b.clone()],
            Some(&opt_b),
            &hyp_refs,
            &ev_refs,
        )?;
        decision_ids.push(decision_id);
    }

    Ok(TenantDataset {
        tenant_id,
        name,
        decision_ids,
        evidence_id,
        hypothesis_id,
    })
}

/// Assert that no events from `other` are readable as `scope`, and that a graph
/// rebuilt for `scope` contains none of `other`'s decisions.
pub fn assert_tenant_isolation<L: EventLedger>(
    ledger: &L,
    scope: &TenantDataset,
    other: &TenantDataset,
) -> TestResult<()> {
    let events = ledger.read_for_tenant(&scope.tenant_id, 0, 1_000)?;

    for event in &events {
        assert_eq!(
            event.tenant_id, scope.tenant_id,
            "event with wrong tenant_id found when reading for '{}': got '{}'",
            scope.name, event.tenant_id,
        );
    }

    let payload_decision_ids: std::collections::HashSet<&str> = events
        .iter()
        .filter_map(|e| e.payload.get("decision_id").and_then(|v| v.as_str()))
        .collect();

    for other_id in &other.decision_ids {
        assert!(
            !payload_decision_ids.contains(other_id.as_str()),
            "decision '{}' from tenant '{}' leaked into event stream for tenant '{}'",
            other_id,
            other.name,
            scope.name,
        );
    }

    let graph = MemoryGraph::default();
    rebuild_graph_for_tenant(ledger, &scope.tenant_id, &graph)?;

    for other_id in &other.decision_ids {
        let rows = graph.query(
            "MATCH (d:`Decision` {id: $id}) RETURN d.id AS id LIMIT 1;",
            &GraphParams::from([("id".to_owned(), GraphValue::String(other_id.clone()))]),
        )?;
        assert!(
            rows.is_empty(),
            "decision '{}' from tenant '{}' appeared in graph rebuilt for tenant '{}'",
            other_id,
            other.name,
            scope.name,
        );
    }

    Ok(())
}

/// Assert that all of a tenant's own decisions are visible in their event stream.
pub fn assert_tenant_completeness<L: EventLedger>(
    ledger: &L,
    dataset: &TenantDataset,
) -> TestResult<()> {
    let events = ledger.read_for_tenant(&dataset.tenant_id, 0, 1_000)?;
    let payload_decision_ids: std::collections::HashSet<&str> = events
        .iter()
        .filter_map(|e| e.payload.get("decision_id").and_then(|v| v.as_str()))
        .collect();

    for decision_id in &dataset.decision_ids {
        assert!(
            payload_decision_ids.contains(decision_id.as_str()),
            "decision '{}' for tenant '{}' not found in event stream",
            decision_id,
            dataset.name,
        );
    }

    Ok(())
}

/// Assert that the graph rebuilt for a tenant contains all of that tenant's decisions.
pub fn assert_graph_completeness<L: EventLedger>(
    ledger: &L,
    dataset: &TenantDataset,
) -> TestResult<()> {
    let graph = MemoryGraph::default();
    rebuild_graph_for_tenant(ledger, &dataset.tenant_id, &graph)?;

    for decision_id in &dataset.decision_ids {
        let rows = graph.query(
            "MATCH (d:`Decision` {id: $id}) RETURN d.id AS id LIMIT 1;",
            &GraphParams::from([("id".to_owned(), GraphValue::String(decision_id.clone()))]),
        )?;
        assert!(
            !rows.is_empty(),
            "decision '{}' for tenant '{}' missing from rebuilt graph",
            decision_id,
            dataset.name,
        );
    }

    Ok(())
}
